movies_list/src/Entity/PlayList.php
<?php

namespace App\Entity;
use App\Entity\Api;
use App\Entity\ApiRequest;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlayListRepository")
 */
class PlayList
{

    public function remove()
    {
        $a=1;

    }
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Description="";

    /**
     * @ORM\Column(type="datetime")
     */
    private $Creation_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $IdOwner;

    /**
     * @ORM\Column(type="datetime")
     */
    private $LastUpdate_at;

    /**
     * @ORM\Column(type="integer")
     */
    private $TypeOf;

    /**
     * @ORM\Column(type="integer")
     */
    private $Accessibility;

    /**
     * @ORM\Column(type="integer")
     */
    private $IdDB;


    public function getShortName(): ?string
    {
        return substr($this->getName(),0,10);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getCreationAt(): ?\DateTimeInterface
    {
        return $this->Creation_at;
    }

    public function setCreationAt(\DateTimeInterface $Creation_at): self
    {
        $this->Creation_at = $Creation_at;

        return $this;
    }

    public function getIdOwner(): ?int
    {
        return $this->IdOwner;
    }

    public function setIdOwner(int $IdOwner): self
    {
        $this->IdOwner = $IdOwner;

        return $this;
    }

    public function getLastUpdateAt(): ?\DateTimeInterface
    {
        return $this->LastUpdate_at;
    }

    public function setLastUpdateAt(\DateTimeInterface $LastUpdate_at): self
    {
        $this->LastUpdate_at = $LastUpdate_at;

        return $this;
    }

    public function getTypeOf(): ?int
    {
        return $this->TypeOf;
    }

    public function setTypeOf(int $TypeOf): self
    {
        $this->TypeOf = $TypeOf;

        return $this;
    }

    public function getAccessibility(): ?int
    {
        return $this->Accessibility;
    }

    public function setAccessibility(int $Accessibility): self
    {
        $this->Accessibility = $Accessibility;

        return $this;
    }

    public function getIdDB(): ?int
    {
        return $this->IdDB;
    }

    public function setIdDB(int $IdDB): self
    {
        $this->IdDB = $IdDB;

        return $this;
    }
}

movies_list/templates/pages/home.html copy.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
<div class="row justify-content-center">

<div class="site-section">
      <div class="container">
        <div class="row">
          <div class="col-lg-8">

            <div class="row">
              <div class="col-lg-6">
                
                <div class="d-block d-md-flex listing vertical">
                  <a href="#" class="img d-block" style="background-image: url('images/img_1.jpg')"></a>
                  <div class="lh-content">
                    <span class="category">Cars &amp; Vehicles</span>
                    <a href="#" class="bookmark"><span class="icon-heart"></span></a>
                    <h3><a href="#">Red Luxury Car</a></h3>
                    <address>Don St, Brooklyn, New York</address>
                    <p class="mb-0">
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-secondary"></span>
                      <span class="review">(3 Reviews)</span>
                    </p>
                  </div>
                </div>

              </div>
              <div class="col-lg-6">

                <div class="d-block d-md-flex listing vertical">
                  <a href="#" id="image_api1" class="img d-block" style="background-image: url('images/img_2.jpg')"></a>
                  <div class="lh-content">
                    <span class="category">Real Estate</span>
                    <a href="#" class="bookmark"><span class="icon-heart"></span></a>
                    <h3><a href="#">House with Swimming Pool</a></h3>
                    <address>Don St, Brooklyn, New York</address>
                    <p class="mb-0">
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-secondary"></span>
                      <span class="review">(3 Reviews)</span>
                    </p>
                  </div>
                </div>

              </div>
              <div class="col-lg-6">
                
                <div class="d-block d-md-flex listing vertical">
                  <a href="#" class="img d-block" style="background-image: url('images/img_1.jpg')"></a>
                  <div class="lh-content">
                    <span class="category">Cars &amp; Vehicles</span>
                    <a href="#" class="bookmark"><span class="icon-heart"></span></a>
                    <h3><a href="#">Red Luxury Car</a></h3>
                    <address>Don St, Brooklyn, New York</address>
                    <p class="mb-0">
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-secondary"></span>
                      <span class="review">(3 Reviews)</span>
                    </p>
                  </div>
                </div>

              </div>
              <div class="col-lg-6">

                <div class="d-block d-md-flex listing vertical">
                  <a href="#" class="img d-block" style="background-image: url('images/img_2.jpg')"></a>
                  <div class="lh-content">
                    <span class="category">Real Estate</span>
                    <a href="#" class="bookmark"><span class="icon-heart"></span></a>
                    <h3><a href="#">House with Swimming Pool</a></h3>
                    <address>Don St, Brooklyn, New York</address>
                    <p class="mb-0">
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-warning"></span>
                      <span class="icon-star text-secondary"></span>
                      <span class="review">(3 Reviews)</span>
                    </p>
                  </div>
                </div>

              </div>

            </div>

            <div class="col-12 mt-5 text-center">
              <div class="custom-pagination">
                <span>1</span>
                <a href="#">2</a>
                <a href="#">3</a>
                <span class="more-page">...</span>
                <a href="#">10</a>
              </div>
            </div>

          </div>
          <div class="col-lg-3 ml-auto">

            <div class="mb-5">
              <h3 class="h5 text-black mb-3">Movies list</h3>
                <div class="form-group">
                  <input type="text" id="new_list_name" name="new_list_name" placeholder="What are you looking for?" class="form-control">
                  <button id="add_new_list" name="add_new_list" class="btn-primary" type="submit">New list</button>
                  <button id="test_api" name="test_api" class="btn-primary" type="submit">Test api</button>

                </div>

            </div>
            

          </div>

        </div>
      </div>
    </div>


</div>

{% endblock %}

movies_list/templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Home{% endblock %}

{% block body %}
<div class="row justify-content-center">

<div class="site-section">
      <div class="container">
        {% set cur = 0 %}
        {#{ dump (movies) }#}
        {% for i in 0..4 %}
          <div class="row">
            {% for c in 0..3 %}
              {% if  movies[cur] is defined %}
                {% set movie = movies[cur] %}
                
                {% if (not movie.media_type is defined) or (movie.media_type == 'tv' or movie.media_type == 'movie' )%}
                {% set movie_title = movie.title is defined?movie.title:movie.original_name %}
                {% set movie_media_type = movie.media_type is defined?movie.media_type:'movie' %}
                {% set movie_release_date = movie.release_date is defined?movie.release_date:movie.first_air_date is defined?movie.first_air_date:'' %}
                {% if app.user %}
                  {% set heart_class = 'add-as-favorite' %}
                  {% if movies_pl_map[movie.id] is defined %}
                    {% for playlist in movies_pl_map[movie.id] %}
                      {% if playlist.idDb == favorite_pl_id %}
                      {% set heart_class = 'movie-is-favorite' %}
                      {% endif %}
                    {% endfor %}
                  {% endif %}                    
                {% else %}
                  {% set heart_class = '' %}
                {% endif %}


                  <div class="col-md-4 col-lg-3 mb-3 mb-lg-3">
                    <div class="h-entry" >
                      <div class="row">
                      <div class="col-md-12"> 
                        <h6 class="font-size-regular"><a href="{{ path('movie',{id:movie.id , media_type:movie_media_type})}}" class="text-black">{{ movie_title }}</a></h6> 
                      </div>
                      <div class="col-md-12"> 
                        <div class="movie-image-content">
                        {% if  movie.poster_path != null %}
                          <a href="{{ path('movie',{id:movie.id, media_type:movie_media_type})}}">
                            <img src="{{ imagebase }}{{ movie.poster_path }}" alt="Image" class="img-fluid rounded" style="margin-bottom: 0px;">
                          </a>
                        {% else %}
                            <p>No image</p>

                        {% endif %}
                             {% if app.user %}
                            <div movie_id ="{{ movie.id }}" class="{{heart_class}}"><span class="icon-heart"></span></div>
                            
                            <snap class="playlist-wrap">
                              <div class="row text-left movies-genres aos-init aos-animate" data-aos="fade-up" data-aos-delay="300">
                                <div class="col-12" id="mv_{{movie.id}}_pl_parent_">
                                  <a id="mv_{{movie.id}}_pl_add_" id_movie="{{ movie.id }}" class="add-new">+</a>
                                <a  id="mv_{{movie.id}}_pl_model_" style="display:none"></a>

                                  {% if movies_pl_map[movie.id] is defined %}
                                    {% for pl_list in movies_pl_map[movie.id] %}
                                      {% if pl_list.idDb != favorite_pl_id %}
                                        <a  class="movie_playlist_item" id="mv_{{movie.id}}_pl_{{pl_list.idDb}}_" id_movie="{{movie.id}}" id_playlist="{{pl_list.idDb}}">{{ pl_list.shortName }} </a>
                                      {% endif %}      
                                    {% endfor %}
                                  {% endif %}


                                </div>
                              </div>   
                            </snap>   
                            {% endif %}   
                            </div>            
                                
                        </div>
                        </div>
                      <div class="row">
                      <div class="col-md-12"> 

                      <!--
                      {% if movie_release_date is defined %}
                        <div class="meta mb-3">Release at {{ movie_release_date }} </div>
                      {% endif %}
                      -->
                      <p><h6 style="font-size: 11px;">{{ movie.overview | slice (0,100) }} ...</h6></p>
                    </div>  
                    </div> 
                    </div> 
                  </div>
                  {% set cur = cur + 1 %}
                {% endif %} 
              {% endif %} 
            {% endfor %}
          </div>
        {% endfor %}
<!--
            <div class="col-12 mt-5 text-center">
              <div class="custom-pagination">
                <span>1</span>
                <a href="{{ path('home',{page:2})}}">2</a>
                <a href="#">3</a>
                <span class="more-page">...</span>
                <a href="#">10</a>
              </div>
            </div>
-->
          </div>
        </div>
      </div>
    </div>


</div>

{% endblock %}